version: "3.3"
services:
  decrypt:
    build:
      context: ~/json2securexml-main/
    command: ["decrypt.py", "encrypted.xml", "--decrypt"] 
    depends_on:
    - encrypt
    volumes:
    - ~/json2securexml-main/assignment/:/usr/src/app:rw
  encrypt:
    command: ["encrypt.py", "sample.json", "--genrate", "--encrypt"] 
    build:
      context: ~/json2securexml-main/
    volumes:
    - ~/json2securexml-main/assignment/:/usr/src/app:rw
